
version: "3.9"
services:
  frontend:
    build: ./services/frontend
    ports:
      - "5173:80"

  api:
    build: ./services/api
    ports:
      - "8080:8080"
    environment:
      - OMR_URL=http://omr:8090/grade
      - DATABASE_URL=postgresql+asyncpg://omr:omr@db/omr
    depends_on:
      - db
      - omr

  omr:
    build: ./services/omr
    ports:
      - "8090:8090"

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: omr
      POSTGRES_PASSWORD: omr
      POSTGRES_DB: omr
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
