name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  lint-frontend:
    name: Lint & Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: |
          cd services/frontend
          npm ci
      - name: Lint
        run: |
          cd services/frontend
          npm run lint
      - name: Run Jest tests
        run: |
          cd services/frontend
          npm run test -- --ci --reporters=default

  lint-backend:
    name: Lint & Test Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          cd services/api
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
      - name: Lint
        run: |
          cd services/api
          pre-commit run --all-files
      - name: Run Pytest
        run: |
          cd services/api
          pytest -q

  build-and-push-api:
    name: Build & Push API Docker Image
    needs: [lint-frontend, lint-backend]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push API Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/api:${GITHUB_REF#refs/tags/} \
            -f services/api/Dockerfile services/api
          docker push ghcr.io/${{ github.repository }}/api:${GITHUB_REF#refs/tags/}

  build-and-push-frontend:
    name: Build & Push Frontend Docker Image
    needs: build-and-push-api
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install and Build
        run: |
          cd services/frontend
          npm ci
          npm run build
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push Frontend Image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository }}/frontend:${GITHUB_REF#refs/tags/} \
            -f services/frontend/Dockerfile services/frontend
          docker push ghcr.io/${{ github.repository }}/frontend:${GITHUB_REF#refs/tags/}